{{- if and .Values.litellm.enabled .Values.litellm.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ai-gateway.litellm.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-gateway.litellm.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.litellm.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "ai-gateway.litellm.selectorLabels" . | nindent 6 }}
{{- end }}
