{{- if and .Values.litellm.enabled .Values.litellm.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai-gateway.litellm.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-gateway.litellm.labels" . | nindent 4 }}
  {{- with .Values.litellm.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
